### PR TITLE
revert deprecation of link tag

### PR DESCRIPTION
**Pull request by ashnazg**
(decision **was** previously made to revert this deprecation (https://github.com/phpDocumentor/fig-standards/issues/104#issuecomment-138111143)
(replaces PR #136)

### CODE REVIEW

**Comment by ashnazg** [comment]
Ping @ondrejmirtes @muglug @neuro159 @mindplay-dk @GaryJones @mvriel @jaapio for opinions.

**Comment by mindplay-dk** [comment]
I think this is fine, but I still think we should consider [making the `@link` and `@see` tags fully interchangible](https://github.com/phpDocumentor/fig-standards/issues/104) - people get them mixed up, and often use whichever one *sounds* right in a given situation.

**Comment by jaapio** [comment]
Fully agree with you

**Comment by ashnazg** [comment]
This change is now being considered on https://github.com/php-fig/fig-standards/pull/1099.

**Pull request closed without merging**
